name: Build

on:
  schedule:
    - cron: "30 03 14 */3 *" # every 3 months (to refresh expired artifacts)
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements_win.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --clean --noconfirm "Code Launcher.spec"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: dist/*

  build-mac-m1:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --clean --noconfirm "Code Launcher.spec"
          cd dist/
          zip -r9 "Code Launcher" "Code Launcher.app/"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-arm
          path: dist/Code Launcher.zip
